sudo: required

services:
    - docker

language: python

env:
  global:
    secure: "iHkMB3uizTIfpPS/A7mxUieUQez/ynNcyYh4JqfAdsZJT4AIxdNMuscWUGXovM2TYOzd9hKMp7GAKxrN2n0adKIardyhT/aKAQbZYOIctpYT8UtiZkTp6FtLMAozas4vt5alV5oR/rfDYSRAXfCpYfqqAsKKzKmqf4zaKOfBUKXdR8kdo9VVPghffcC11hQ3KEFdSrYc8iCPlhc4Wl3G2lG00V54Td6ifzTk9bkyZ2m2JR/Xv1UVv5TniRof7SOF44vBymshwoYvleOYOX5ss6f4doVvzjQADgK0n1CajoPOz+4kSsbHPBlz+JnCcvfHCEpxvKXzuN98H9r7Hu5iFANyov8kNmivuZFbMQ9aIhphSpOlzTYjH1UEv3fxCF2p5gLuRjouVCLb5srs/+srKrHjstoNXJAYQwO2/9D/h2OkqY5GsAgFD3nCwDR19FmrHhhC+hywhlZuptwNe/31B8opq1/A1J/6Vdn5TDAgjZfEIFb8+fxpnnR2qgwbOKXHkR6Eq5OuzvKC74IkVKmpTGQVaPrW0UrdmsyyK4YVP7aCWk2K5BRhx8iyGgTVxU6wBs4R7YrmNNDbQfOOImO7SNBiiK2Uq7MNRbenw/tr+nwfL7PyBSm/DWTtSw5kGU2bZ9bKWnx/J+kx9/6pjO3+IU1+yRUWKkHDWxg8lTVXBuU="

branches:
  except:
    - debian

install:
    - pip install codecov
    - docker-compose build
    - docker-compose up -d
    - sleep 3

script:
    - docker-compose exec -T tango-test python3 -m pip install -r dev-requirements.txt
    - docker-compose exec -T tango-test python3 -m pip install .
    - docker-compose exec -T tango-test python3 -m flake8
    - docker-compose exec -T tango-test python3 -m pytest --cov=BeamlineStatusLogger --cov-report xml:coverage.xml

after_success:
    - sudo chown travis:travis .coverage coverage.xml
    - codecov

before_deploy:
    - .ci/travis/deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "E8Oqs3rAv7Q3MAIeeSe/ESe5D1qAbScremu1Ntz/kSuH6Kqq5fvmixL+UPbrvN53QtuFhIsB475XZRorsbRPFUMWXY44nfLOSYhvCxAYEK4JjTP6HsEHn2zjY5ODEQQ4jQHuGEOmmir9XVRscBPcR6Bicdw1QP0xiwLMsH/6CR8TISyDayeEYatnUxzFdBzyBAlDSYvL4mcbaCybhqvSmyr87PWudO+8Q0DoxCw3FkDLKxCJvfILBF7bI+m3WtEkfOz6YJl0L+V1YJ08q14dLX12Qx1uhFVCb9QZ6ND0bxm+AzDUWN0g8fSuZh+MFww9eRITdd+o4fEgcA1dIy29jvw7hu7yFNS3ujowNyuj2BWGLZgZ2ouhEyuAUKSppKs59GcivdbKEPXxxrKvg50dVXbmlSE20Od7cE5p9MuUseW4BjvS7VoiuAHc14+C2aRQkCqr8PuQCmae0Eg6hRPMab/MZqlcED4gzvJZyKrVg4y9CaYylppGztYda6aocqwVbhM6PtNkonkcqBwOnfKQ9g3mXK4iyjUfnaGEsQ/8vJDIT0jbS8R4GWkUuRiyMpYBczIk82WyXNSvNn1nvy4JNTa1QTQZiIzj0/s8T4DCWOlwV0Vd+HT8E16b9gnotgCwgDHwbaTGEI+c61NoduYV1u6GXNMOUAwz8j8WxlEt4JM="
  file_glob: true
  file: "*.deb"
  skip_cleanup: true
  on:
    repo: DESY-P02-1/BeamlineStatusLogger
    tags: true
