version: '2'
services:
  influxdb-test:
    image: "influxdb"
    expose:
      - "8086"
  tango-test:
    build: ".ci/debian9"
    image: tango-test
    depends_on:
      - influxdb-test
    environment:
      - INFLUXDB_HOST=influxdb-test
    volumes:
     - .:/code
